config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users
  resources :friendships

  resources :posts do
    resources :reviews
    resources :comments, :controller => 'post_comments'
  end

  root 'posts#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :post_groupships
  has_many :posts, :through => :post_groupships
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :reviews

  belongs_to :user
  has_many :attendees
  has_many :comments
  belongs_to :category
  validates_presence_of :name

  has_many :post_groupships
  has_many :groups, :through => :post_groupships

  def post_count!
    self.post_count ||= 0
    self.post_count += 1
    self.save
  end
end

app/models/post_groupship.rb
class PostGroupship < ActiveRecord::Base
  belongs_to :post
  belongs_to :group
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice]="added friend."
      redirect_to users_path
    else
      flash[:error] = "unable to add friend"
      redirect_to users_path
    end
  end

  def show

    @friendship = current_user.friendships.find(params[:id])
  end

  def destroy
    @friendship = current_user.friendships.find_by_friend_id(params[:friend_id])
    @friendship.destroy

    flash[:notice] = "Removed friendship."
    redirect_to users_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!, :except => [:index]
  before_action :set_post, :only => [ :show, :edit, :update, :destroy]
  # before_filter :authenticate, except: [:index, :show]

  def index

    @groups = Group.all
    @comments = Comment.all
    @posts = Post.page(params[:page]).per(5)

    # if params[:post_i] && current_user == Post.find(params[:post_i]).user
    #   @post = Post.find(params[:post_i])
    # else
      @post = Post.new
    # end

    @posts = Post.order(sort_column+" "+sort_direction).page(params[:page]).per(5)


    if params[:order] # Parameter: {:xxx => "fdsuifd", :order => "sdf"}
      if params[:order] == 'name'
        sort_by = params[:order]
      elsif params[:order] == 'created_at'
        sort_by = params[:order]
      elsif params[:order] == 'post_count'
        sort_by = params[:order]
      elsif params[:order] == 'comment_number'
        sort_by = params[:order]
      end
      @posts = @posts.order(sort_by)
    end

    if params[:group_id]
      @posts = Group.find(params[:group_id]).posts.page(params[:page]).per(5)
    end

  end


  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :action => :new
    end
    flash[:notice] = "event was successfully created"
  end

  def show
    if cookies.signed["view-topic-#{@post.id}-user-#{current_user.id}"].nil?
      @post.post_count!
      cookies.signed["view-topic-#{@post.id}-user-#{current_user.id}"]  = Post.find("#{@post.id}")

    end

    @reviews = Review.where(post_id: @post)
    if @reviews.blank?
      @raty = 0
    else
      @raty = @reviews.average(:rating).round(2)
    end
  end

  def update
    if current_user && @post.user == current_user
      @post.update(post_params)

      redirect_to posts_path(:page => params[:post][:page])
    end
    flash[:notice] = "event was successfully updated"
  end

  def destroy
    @post.destroy

    redirect_to posts_path(:page=> params[:page])
    flash[:alert] = "event was successfully deleted"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :description, :category_id,:group_ids =>[])

  end

  # def authenticate
  #   redirect_to posts_path unless current_user == @post.user
  # end

  def sort_column
    Post.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_post

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create

    @review = Review.new( :rating => params[:rating] )
    @review.post = @post
    @review.save
    @reviews = Review.where(post_id: @post)

    if @reviews.blank?
      @raty = 0
    else
      @raty = @reviews.average(:rating).round(2).to_f
    end


    respond_to do |format|
       format.js
    end

  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:keyword] == nil
      @users = current_user.friends
    else params[:keyword]
      @users = User.where(["email like?", "%#{params[:keyword]}%"])
    end



    # @users = User.all unless @users.present?
  end

  def show
    @user = User.find(params[:id])

    @user_commented_posts = Post.where(id: current_user.comments.pluck(:post_id).uniq)
  end

  private

  def event_params
    params.require(:user).permit(:id  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/post_attendees_helper.rb
module PostAttendeesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.collection_select(:category_id, Category.all, :id, :name) %>
<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
<p>
<%= f.label:name, "Name" %>
<%= f.text_field :name %>
<%#= f.hidden_field :page, @page %>
</p>
<div class="form-group">
  <%= f.label:description, "Context" %>
  <%= f.text_area :description %>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= render :partial => 'form', :locals => {:f=>f} %>
  <%= f.submit "update" %>
<% end %>

app/views/posts/index.html.erb
<p>
<%= link_to "Search User", users_path %>
</p>
<h2>New Post</h2>
<%= form_for ([ @post]) do |f| %>
  <p><%= render :partial => 'form', :locals=> {:f=> f }%></p>
  <p><%= f.hidden_field(:page, value: params[:page]) %></p>
  <p><%= f.submit "Update" %></p>
<% end %>

<table class="sort">
  <tr>
    <td><%= sortable "name", "Sort_by_names" %></td>
    <td><%= sortable "created_at", "Sort_by_created" %></td>
    <td><%= sortable "comment_number", "Sort_by_Comment_number" %></td>
    <td><%= sortable "post_count", "Sort_by_views" %></td>
  </tr>
</table>

<p>
<% @groups.try(:each) do |g| %>
  <%= link_to g.name, posts_path(:group_id => g, :page => params[:page]) %>
<% end %>
</p>


<table class="table table-hover">
  <tr>
    <td><h3>Post</h3></td>
    <td><h3>Author</h3></td>
    <td><h3>star</h3></td>
    <td><h3>Created time</h3></td>
    <td><h3>Last Comment Created time</h3></td>
    <td><h3>Comment counts</h3></td>
    <td><h3>views counts</h3></td>
    <td><h3>Function</h3></td>
  </tr>
  <% @posts.try(:each) do |post| %>
    <tr>
      <td>
        <%=link_to post.name, post_path(post) %>
      </td>
      <td>
        <%= post.user.try(:email) %>
      </td>
      <td>
        <div id="rateYo"></div>
      </td>
      <td>
        <%= post.created_at %>
      </td>
      <td>
        <%= post.try(:comments).last.try(:updated_at) %>
      </td>
      <td>
        <%= post.try(:comment_number) %>
      </td>
      <td>
        <%= post.post_count %>
      </td>
      <td>
        <% if current_user == post.user  %>
          <%= link_to 'Show', post_path(post),:class=> "btn btn-default"%>
          <%= link_to 'Edit', posts_path(:post_i => post, page: params[:page]),:class=> "btn btn-default" %>
          <%= link_to 'Delete', post_path(post,page: params[:page]), :method=> :delete, :class=> "btn btn-default" %>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>
<p><%= link_to 'New Post', new_post_path %></p>

<p><%= paginate @posts %></p>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for @post, url:posts_path do |f| %>
  <p><%= render :partial => 'form', :locals=> {:f=> f }%></p>
  <p><%= f.submit "Create" %></p>
<% end %>

app/views/posts/show.html.erb
<p>Category: <%= @post.category.try(:name) %><p>

<h3>View count:<%= @post.post_count %></h3>

<p>Group:
<% @post.groups.each do |g| %>
  <%= g.name %>
<% end %>
</p>
<h3>Title:</h3>
<div><%= @post.name %></div>
<h4>Context:</h4>
<div>
  <p><%=simple_format @post.description %></p>
</div>

<div id="rateYo"></div>
<!-- <button class="button" id="hello">give reviews</button> -->
<%= link_to "give reviews", post_reviews_path(@post), method: :post, remote: true, class: "button" %>

<p><div id="content"><%= @raty %></div></p>

<%= link_to "Back to homepage", posts_path %>

<h4><%= @post.try(:comment_number) %>Comments</h4>

<div class="panel-footer">
  <%= render :partial=> 'post_comments/comment' %>
</div>

</div>
<h4>Add a comment:</h4>
<%= render "post_comments/form" %>


<script>

$(function () {

  $("#rateYo").rateYo({
    starWidth: "40px",
    numStars: 5,
    halfStar: true,
    rating: <%= @raty %>
  });
});




  $(function () {

  var $rateYo = $("#rateYo").rateYo();

  $(".button").click(function () {
    /* get rating */
    var rating = $rateYo.rateYo("rating");
      var post_id =  <%= @post.id %>;
      $.ajax({
        type: 'POST',
        url: "/posts/" + post_id + "/reviews",
        dataType: 'JSON',
        data: {
          // user_id: <%= current_user %>
          rating: rating
        },
        success: function(){
          // $("#content").html("asd");
        }
      });
  });

});

</script>

app/views/users/index.html.erb
<p>
<%= link_to "Back_to_index", posts_path %>
</p>

<p>
<%= form_tag users_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>
<p>

<p>
</p>

<table class="table table-hover">
  <tr>
    <td><h3>Email</h3></td>
    <td><h3>NAME</h3></td>
  </tr>
  <% @users.try(:each) do |u| %>
    <tr>
      <td>
        <%= link_to u.email, user_path(u) %>
      </td>
      <td>
        <%= u.try(:first_name) %>
      </td>
      <td>
        <%= link_to "Add Friend", friendships_path(:friend_id => u), :method => :post %>
      </td>
    </tr>
  <% end %>

</table>

app/views/users/show.html.erb
<table class="table table-striped">
  <tr>
    <td><h3>First Name</h3></td>
    <td><%= @user.first_name %></td>
  </tr>
  <tr>
    <td><h3>Last Name</h3></td>
    <td><%= @user.last_name %></td>
  </tr>
  <tr>
    <td><h3>Email</h3></td>
    <td><%= @user.email %></td>
  </tr>
</table>

<h3>Friends</h3>
<ul>
  <% for friend in @user.friends %>
    <li>
      <%= friend.email %>
      (<%= link_to "remove", friendship_path(:friend_id => friend.id), :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>

<h2>Friended by Users</h2>
<ul>
  <% for user in @user.inverse_friends %>
    <li><%= user.email %></li>
  <% end %>
</ul>


<% @user_commented_posts.each do |p| %>
  <p><%= link_to p.name, post_path(p) %><p>
<% end %>

app/views/users/user.html.erb
dfgfgsd